# Generated by Django 3.1.4 on 2021-01-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201228_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
