# Generated by Django 3.1.4 on 2021-01-15 19:57

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_dish_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('photo_sm', models.ImageField(null=True, upload_to=menu.models.Anons.get_file_name_anonses)),
                ('photo_bg', models.ImageField(null=True, upload_to=menu.models.Anons.get_file_name_anonses)),
                ('description', models.CharField(max_length=300, null=True)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
    ]
